[project]
name = "agente-csv-llm"
version = "0.1.0"
description = "Agente de análise de arquivos CSV com LLM local via Streamlit"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "streamlit",
    "pandas",
    "langchain",
    "langchain-ollama"
]
